remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Biomedical Visual Instruction Tuning with Clinician Preference Alignment"
description: "Hejie Cui, Lingjun Mao, Xin LIANG, Jieyu Zhang, Hui Ren, Quanzheng Li, Xiang Li, Carl Yang"
